In [283]:
import numpy as np
import pandas as pd
import re

In [331]:
csv_folder = "scenarios/CaDiCaL/slices-BMC08/"
csv_name = "configs_old_Copy.csv"

df1 = pd.read_csv(csv_folder + csv_name, header=None, sep="'(.*?)'", engine="python")
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,115,116,117,118,119,120,121,122,123,124
0,"pCOMPACTINT-0, -arena",3,-arenacompact,True,-arenasort,1,-binary,True,-check,False,...,0.1,-vivify,True,-vivifymaxeff,10000000.0,-vivifymineff,100000.0,-vivifyreleff,0.03,NaN
1,"pCOMPACTINT-1, -arena",3,-arenacompact,True,-arenasort,1,-binary,True,-check,False,...,0.1,-vivify,True,-vivifymaxeff,10000000.0,-vivifymineff,100000.0,-vivifyreleff,0.03,NaN
2,"pCOMPACTINT-2, -arena",3,-arenacompact,True,-arenasort,1,-binary,True,-check,False,...,0.1,-vivify,True,-vivifymaxeff,10000000.0,-vivifymineff,100000.0,-vivifyreleff,0.03,NaN
3,"pCOMPACTINT-3, -arena",3,-arenacompact,True,-arenasort,1,-binary,True,-check,False,...,0.1,-vivify,True,-vivifymaxeff,10000000.0,-vivifymineff,100000.0,-vivifyreleff,0.03,NaN
4,"pCOMPACTINT-4, -arena",3,-arenacompact,True,-arenasort,1,-binary,True,-check,False,...,0.1,-vivify,True,-vivifymaxeff,10000000.0,-vivifymineff,100000.0,-vivifyreleff,0.03,NaN

In [332]:
df1.drop(columns=np.arange(len(df1.columns), step=2), inplace=True)
df1.head()

,1,3,5,7,9,11,13,15,17,19,...,105,107,109,111,113,115,117,119,121,123
0,3,True,1,True,False,True,375,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
1,3,True,1,True,False,True,2534,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
2,3,True,1,True,False,True,3973,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
3,3,True,1,True,False,True,4933,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
4,3,True,1,True,False,True,5573,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03

In [333]:
with open(csv_folder + csv_name, 'r') as csvfile:
    one_line_text = csvfile.readline()

regr =" -(.*?) " 

col_names = re.findall(regr,one_line_text)
df1.columns = col_names
df1.head()

,arena,arenacompact,arenasort,binary,check,compact,compactint,compactlim,compactmin,decompose,...,subsumeinit,subsumeocclim,transred,transredmaxeff,transredmineff,transredreleff,vivify,vivifymaxeff,vivifymineff,vivifyreleff
0,3,True,1,True,False,True,375,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
1,3,True,1,True,False,True,2534,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
2,3,True,1,True,False,True,3973,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
3,3,True,1,True,False,True,4933,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
4,3,True,1,True,False,True,5573,0.1,100,True,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03

In [334]:
df2 = pd.read_csv(csv_folder+csv_name, header=None, sep="p(.*?) ", engine="python")
df2[1].head()

0    COMPACTINT-0,
1    COMPACTINT-1,
2    COMPACTINT-2,
3    COMPACTINT-3,
4    COMPACTINT-4,
Name: 1, dtype: object

In [335]:
df1.insert(0, "parameter", df2[1])
df1.head()

,parameter,arena,arenacompact,arenasort,binary,check,compact,compactint,compactlim,compactmin,...,subsumeinit,subsumeocclim,transred,transredmaxeff,transredmineff,transredreleff,vivify,vivifymaxeff,vivifymineff,vivifyreleff
0,"COMPACTINT-0,",3,True,1,True,False,True,375,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
1,"COMPACTINT-1,",3,True,1,True,False,True,2534,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
2,"COMPACTINT-2,",3,True,1,True,False,True,3973,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
3,"COMPACTINT-3,",3,True,1,True,False,True,4933,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03
4,"COMPACTINT-4,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.03

In [336]:
def manipulate_df(df, target):
    
    cols = list(df.columns[1:])
    
    cols.remove(target)
    
    target_values = list(df1.loc[df1.parameter.apply(lambda x:x.split('-')[0]) == target.upper(), target])
        
    with open(csv_folder+csv_name, 'r') as csvfile:
        regr = target + " '(.*?)'" 

        lines = csvfile.readlines()
        new_lines = []
        for i in range(len(lines)):
            result = re.search(regr,lines[i]).span()
            
            for ix, value in enumerate(target_values):
                line_id,line_conf= lines[i].split(',')
                new_line_id = line_id + '_' + target.upper() + '-'+str(ix) + ','
                
                new_lines.append(new_line_id+line_conf.replace(lines[i][result[0]:result[1]],target+ f" '{value}'"))
                
        
    with open(csv_folder+"configs_new.csv", "w") as f:
        f.write("#Config ID, configuration call string\n")
        
        for line in new_lines:
            if line.startswith('p'+target.upper()):
                pass
            else:
                f.write(line)
    return df

In [337]:
target ="keepglue"
df3 = manipulate_df(df1, target)
df3

,parameter,arena,arenacompact,arenasort,binary,check,compact,compactint,compactlim,compactmin,...,subsumeinit,subsumeocclim,transred,transredmaxeff,transredmineff,transredreleff,vivify,vivifymaxeff,vivifymineff,vivifyreleff
0,"COMPACTINT-0,",3,True,1,True,False,True,375,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.030000
1,"COMPACTINT-1,",3,True,1,True,False,True,2534,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.030000
2,"COMPACTINT-2,",3,True,1,True,False,True,3973,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.030000
3,"COMPACTINT-3,",3,True,1,True,False,True,4933,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.030000
4,"COMPACTINT-4,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.030000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,"VIVIFYRELEFF-10,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.162667
596,"VIVIFYRELEFF-11,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.233125
597,"VIVIFYRELEFF-12,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.338811
598,"VIVIFYRELEFF-13,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.497340
599,"VIVIFYRELEFF-14,",3,True,1,True,False,True,5573,0.1,100,...,10000,100,True,10000000.0,100000.0,0.1,True,10000000.0,100000.0,0.735134